-- INSERT ALL GIVEN EVENTS DATA
EXEC spAddEvent '6-May-17', 'SQLSaturday #626 - Budapest 2017', 'Budapest', 'Europe/Middle East/Africa', 6;
EXEC spAddEvent '6-May-17', 'SQLSaturday #615 - Baltimore 2017', 'Baltimore', 'Canada/US', 6;
EXEC spAddEvent '13-May-17', 'SQLSaturday #608 - Bogota 2017', 'Bogota', 'Latin America', 6;
EXEC spAddEvent '20-May-17', 'SQLSaturday #616 - Kyiv 2017', 'Kyiv', 'Europe/Middle East/Africa', 6;
EXEC spAddEvent '20-May-17', 'SQLSaturday #588 - New York City 2017', 'New York City', 'Canada/US', 6;
EXEC spAddEvent '27-May-17', 'SQLSaturday #630 - Brisbane 2017', 'Brisbane', 'Asia Pacific', 6;
EXEC spAddEvent '27-May-17', 'SQLSaturday #599 - Plovdiv 2017', 'Plovidv', 'Europe/Middle East/Africa', 6;
EXEC spAddEvent '03-June-17', 'SQLSaturday #638 - Philadelphia 2017', 'Philadelphia', 'Canada/US', 6;


-- INSERT ALL GIVEN PRESENTATION DATA
EXEC spInsertPresentation 'A dive into Data Quality Services', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'A Dynamic World Demands Dynamic SQL', 'Jeremiah', 'Peschka', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'A Dynamic World Demands Dynamic SQL', 'Jeremiah', 'Peschka', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Absolute Introductory Session on SQL Server 2014 In-Memory Optimized Databases (Hekaton)', 'Kevin', 'Goff', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'AlwaysOn: Improve reliability and reporting performance with one cool tech', 'Chris', 'Seferlis', 'Beginner', 'New York City';
EXEC spInsertPresentation 'An introduction to Data Mining', 'Steve', 'Simon', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'An Introduction to Database Design', 'Mohammad', 'Yusuf', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Autogenerating a process data warehouse', 'Kennie', 'Pontoppidan', 'Advanced', 'New York City';
EXEC spInsertPresentation 'Automate your daily checklist with PBM and CMS', 'John', 'Sterrett', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters', 'Thomas', 'Grohser', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters', 'Thomas', 'Grohser', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Automating Execution Plan Analysis', 'Joe', 'Chang', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'Automating Execution Plan Analysis', 'Joe', 'Chang', 'Advanced', 'New York City';
EXEC spInsertPresentation 'Automating SQL Server using PowerShell', 'Michael', 'Wharton', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Balanced Scorecards using SSRS', 'Sunil', 'Kadimdiwan', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Baselines and Performance Monitoring with PAL', 'Mike', 'Walsh', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Basic Database Design', 'John', 'Miner', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Basic Database Programming', 'John', 'Miner', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Become a BI Independent Consultant!', 'James', 'Serra', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'Best Practices Document', 'Paresh', 'Motiwala', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Best Practices for Efficient SSRS Report Creation', 'Mickey', 'Stuewe', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Biggest Loser: Database Edition', 'John', 'Miner', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Building a BI Solution in the Cloud', 'Stacia', 'Misner', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Building an Effective Data Warehouse Architecture', 'James', 'Serra', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Building an Effective Data Warehouse Architecture with the cloud and MPP', 'James', 'Serra', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Bulk load and minimal logged inserts', 'David', 'Peter Hansen', 'Advanced', 'New York City';
EXEC spInsertPresentation 'Business Analytics with SQL Server & Power Map:Everything you want to know but were afraid to ask', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Challenges to designing financial warehouses, lessons learnt', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Change Data Capture in SQL Server 2008/2012', 'Kevin', 'Goff', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Changing Your Habits to Improve the Performance of Your T-SQL', 'Mickey', 'Stuewe', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments', 'Allan', 'Hirt and SIOS Technology', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments', 'Allan', 'Hirt', 'Non-Technical', 'Kyiv';
EXEC spInsertPresentation 'Coffee Break', 'SQLSatruday', '364', 'Non-Technical', 'Budapest';
EXEC spInsertPresentation 'Creating A Performance Health Repository - using MDW', 'Robert', 'Pearl', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Creating efficient and effective SSRS BI Solutions', 'Steve', 'Simon', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Creating efficient and effective SSRS BI Solutions', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Data Partitioning', 'John', 'Flannery', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Data Tier Application Testing with NUnit and Distributed Replay', 'John', 'Flannery', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Database design for mere developers', 'Steve', 'Simon', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Database design for mere developers', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Database Design: Solving Problems Before they Start!', 'Edward', 'Pollack', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Database Modeling and Design', 'Mohammad', 'Yusuf', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Database Virtualization and Drinking out of the Fire Hose', 'Michael', 'Corey', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'DAX and the tabular model', 'Steve', 'Simon', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'DBA FOR DUMMIES', 'Robert', 'Pearl', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'Dealing With Difficult People', 'Gigi', 'Bell', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Development Lifecycle with SQL Server Data Tools and DACFx', 'John', 'Flannery', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Did You Vote Today? A DBAs Guide to Cluster Quorum', 'Allan', 'Hirt', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'Dimensional Modeling Design Patterns: Beyond Basics', 'Jason', 'Horner', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Dimensional Modeling Design Patterns: Beyond Basics', 'Jason', 'Horner', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Diving Into Query Execution Plans', 'Edward', 'Pollack', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Dynamic SQL: Writing Efficient Queries on the Fly', 'Edward', 'Pollack', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Easy Architecture Design for HA and DR', 'Brent', 'Ozar', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Enhancing your career: Building your personal brand', 'James', 'Serra', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Establishing a SLA', 'Thomas', 'Grohser', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'ETL not ELT! Common mistakes and misconceptions about SSIS', 'Paul', 'Rizza', 'Advanced', 'Budapest';
EXEC spInsertPresentation 'Event Kickoff and Networking', 'SQLSaturday', '364', 'Non-Technical', 'New York City';
EXEC spInsertPresentation 'Execution Plans: What Can You Do With Them?', 'Grant', 'Fritchey', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Faster, Better Decisions with Self Service Business Analytics', 'Sayed', 'Saeed', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Full Text Indexing Basics', 'John', 'Miner', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'Get your Mining Model Predictions out to all', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Getting a job with Microsoft', 'Paul', 'Rizza', 'Non-Technical', 'New York City';
EXEC spInsertPresentation 'Graph Databases for SQL Server Professionals', 'St�phane', 'Fr�chette', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Hacking Expos� - Using SSL to Protect SQL Connections', 'Chris', 'Bell', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Hacking the SSIS 2012 Catalog', 'Andy', 'Leonard', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'Hidden in plain sight: master your tools', 'Varsham', 'Papikian', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Highly Available SQL Server in Windows Azure IaaS', 'David', 'Bermingham', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'How to Make a LOT More Money as a Consultant', 'James', 'Serra', 'Beginner', 'New York City';
EXEC spInsertPresentation 'How to Think Like the Engine', 'Brent', 'Ozar', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Hybrid Cloud Scenarios with SQL Server 2014', 'George', 'Walters', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Hybrid Solutions: The Future of SQL Server Disaster Recovery', 'Allan', 'Hirt', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Implementing Data Warehouse Patterns with the Microsoft BI Tools', 'Kevin', 'Goff', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Inroduction to Triggers', 'Jack', 'Corbett', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'Integrating Reporting Services with SharePoint', 'Kevin', 'Goff', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Integration Services (SSIS) for the DBA', 'David', 'Peter Hansen', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Introducing Power BI', 'Stacia', 'Misner', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Introduction to Database Recovery', 'John', 'Flannery', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Introduction to High Availability with SQL Server', 'John', 'Sterrett', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Introduction to Powershell for DBA', 'John', 'Sterrett', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Introduction to SQL Server - Part 1', 'Brandon', 'Leach', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Introduction to SQL Server - Part 2', 'Brandon', 'Leach', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Is That A Failover Cluster On Your Laptop/Desktop?', 'Allan', 'Hirt', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Leaving the Windows Open', 'Jeremiah', 'Peschka', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Lunch Break', 'SQLSaturday', '364', 'Non-Technical', 'New York City';
EXEC spInsertPresentation 'Lunchtime Keynote', 'SQLSaturday', '364', 'Non-Technical', 'New York City';
EXEC spInsertPresentation 'Master Data Services Best Practices', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Master Data Services Disaster Recovery', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Mind your language!! Cursors are a dirty word', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Modern Data Warehousing', 'James', 'Serra', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Monitoring Server health via Reporting Services dashboards', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Monitoring SQL Server using Extended Events', 'Hilary', 'Cotter', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Multidimensional vs Tabular - May the Best Model Win', 'Stacia', 'Misner', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Murder They Wrote', 'Jason', 'Brimhall', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Never Have to Say "Mayday!!!" Again', 'Mike', 'Walsh', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Now you see it! Now you don�t! Conjuring many reports utilizing only one SSRS report.', 'Steve', 'Simon', 'Intermediate', 'New York City';
EXEC spInsertPresentation 'Optimal Infrastructure Strategies for Cisco UCS, Nexus and SQL Server', 'Kevin', 'Schenega', 'Non-Technical', 'Budapest';
EXEC spInsertPresentation 'Optimizing Protected Indexes', 'Chris', 'Bell', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Partitioning as a design pattern', 'Kennie', 'Pontoppidan', 'Advanced', 'Budapest';
EXEC spInsertPresentation 'Power BI Components in Microsofts Self-Service BI Suite', 'Todd', 'Chittenden', 'Beginner', 'New York City';
EXEC spInsertPresentation 'Power to the people!!', 'Steve', 'Simon', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'PowerShell Basics for SQLServer', 'Michael', 'Wharton', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'PowerShell for the Reluctant DBA / Developer', 'Jason', 'Horner', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Prevent Recovery Amnesia � Forget the Backups', 'Chris', 'Bell', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Query Optimization Crash Course', 'Edward', 'Pollack', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Rapid Application Development with Master Data Services', 'Steve', 'Simon', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Recovery and Backup for Beginners', 'Mike', 'Hillwig', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Reduce, Reuse, Recycle: Automating Your BI Framework', 'Stacia', 'Misner', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Replicaton Technologies', 'Hilary', 'Cotter', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'Reporting Services for Mere DBAs', 'Jason', 'Brimhall', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'Scaling with SQL Server Service Broker', 'Hilary', 'Cotter', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'Scaling with SQL Server Service Broker', 'Hilary', 'Cotter', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'Self-Service Data Integration with Power Query', 'St�phane', 'Fr�chette', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Shortcuts to Building SSIS in .Net', 'Paul', 'Rizza', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'So You Want To Be A Consultant?', 'Allan', 'Hirt', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'SQL anti patterns', 'Kennie', 'Pontoppidan', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'SQL Server 2012/2014 Columnstore index', 'Kevin', 'Goff', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'SQL Server 2012/2014 Performance Tuning All Up', 'George', 'Walters', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'SQL Server 2014 Data Access Layers', 'Steve', 'Simon', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'SQL Server 2014 New Features', 'George', 'Walters', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'SQL Server AlwaysOn Availability Groups', 'George', 'Walters', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'SQL Server and the Cloud', 'David', 'Peter Hansen', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'SQL Server Compression and what it can do for you', 'Jason', 'Brimhall', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'SQL Server Reporting Services 2014 on Steroids!!', 'Steve', 'Simon', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'SQL Server Reporting Services Best Practices', 'Steve', 'Simon', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'SQL Server Reporting Services, attendees choose', 'Kevin', 'Goff', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'SQL Server Storage Engine under the hood', 'Thomas', 'Grohser', 'Intermediate', 'Kyiv';
EXEC spInsertPresentation 'SQL Server Storage internals: Looking under the hood.', 'Brandon', 'Leach', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'SSIS 2014 Data Flow Tuning Tips and Tricks', 'Andy', 'Leonard', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Standalone to High-Availability Clusters over Lunch�with Time to Spare', 'Carl', 'Berglund', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Stress testing SQL Server', 'Hilary', 'Cotter', 'Advanced', 'Kyiv';
EXEC spInsertPresentation 'Table partitioning for Azure SQL Databases', 'John', 'Miner', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'Testing', 'Melissa', 'Riley', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'The future of the data professional', 'Adam', 'Jorgensen', 'Beginner', 'Kyiv';
EXEC spInsertPresentation 'The Quest for the Golden Record:MDM Best Practices', 'Dennis', 'Messina', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'The Quest to Find Bad Data With Data Profiling', 'Richie', 'Rump', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'The Spy Who Loathed Me - An Intro to SQL Security', 'Chris', 'Bell', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'Tired of the CRUD? Automate it!', 'Jack', 'Corbett', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Top 5 Ways to Improve Your triggers', 'Aaron', 'Bertrand', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Tricks that have saved my bacon', 'Greg', 'Moore', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'T-SQL : Bad Habits & Best Practices', 'Aaron', 'Bertrand', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'T-SQL for Application Developers - Attendees chose', 'Kevin', 'Goff', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Tune Queries By Fixing Bad Parameter Sniffing', 'Grant', 'Fritchey', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Using Extended Events in SQL Server', 'Jason', 'Brimhall', 'Advanced', 'Budapest';
EXEC spInsertPresentation 'Watch Brent Tune Queries', 'Brent', 'Ozar', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'What every SQL Server DBA needs to know about Windows Server 10 Technical Preview', 'David', 'Bermingham', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'What exactly is big data and why should I care?', 'James', 'Serra', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'What is it like to work for Microsoft?', 'James', 'Serra', 'Beginner', 'Budapest';
EXEC spInsertPresentation 'What�s new in SQL Server Integration Services 2012', 'Kevin', 'Goff', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Why do we shun using tools for DBA job?', 'Paresh', 'Motiwala', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'Why OLAP? Building SSAS cubes and benefits of OLAP', 'Kevin', 'Goff', 'Intermediate', 'Budapest';
EXEC spInsertPresentation 'You''re Doing It Wrong!!', 'Mike', 'Walsh', 'Intermediate', 'Budapest';




-- INSERT ALL GIVEN PEOPLE DATA
EXEC spAddPerson 'Amanda', 'Long', '10 Napa Ct.', 'Lebanon', '97355', 'Oregon', 'ALong@gmail.com';
EXEC spAddPerson 'Christian', 'Shan', '1000 Bidweld Street', 'Haney', 'V2W 1W2', 'British Columbia', 'CShan@gmail.com';
EXEC spAddPerson 'Troy', 'Sara', '1002 N. Spoonwood Court', 'Hervey Bay', '4655', 'Queensland', 'TSara@gmail.com';
EXEC spAddPerson 'Kaitlyn', 'Baker', '1003 Matterhorn Ct', 'Lebanon', '97355', 'Oregon', 'KBaker@gmail.com';
EXEC spAddPerson 'Suzanne', 'Ma', '1005 Matterhorn Ct.', 'Cambridge', 'CB4 4BZ', 'England', 'SMa@gmail.com';
EXEC spAddPerson 'Anna', 'Jones', '1005 Matterhorn Ct.', 'Mill Valley', '94941', 'California', 'AJones@gmail.com';
EXEC spAddPerson 'Carlos', 'Baker', '1005 Tanager Court', 'Corvallis', '97330', 'Oregon', 'CBaker@gmail.com';
EXEC spAddPerson 'Tanya', 'Munoz', '1005 Tanager Court', 'Milsons Point', '2061', 'New South Wales', 'TMunoz@gmail.com';
EXEC spAddPerson 'Tabitha', 'Gill', '1006 Deercreek Ln', 'Bellflower', '90706', 'California', 'TGill@gmail.com';
EXEC spAddPerson 'Alexis', 'Lee', '1006 Deercreek Ln', 'Torrance', '90505', 'California', 'ALee@gmail.com';
EXEC spAddPerson 'Erick', 'Suri', '101 Adobe Dr', 'Coffs Harbour', '2450', 'New South Wales', 'ESuri@gmail.com';
EXEC spAddPerson 'Marcus', 'Evans', '101 Adobe Dr', 'Puyallup', '98371', 'Washington', 'MEvans@gmail.com';
EXEC spAddPerson 'Marcus', 'Clark', '101, avenue de la Gare', 'Peterborough', 'PB12', 'England', 'MClark@gmail.com';
EXEC spAddPerson 'Gilbert', 'Xu', '1010 Maple', 'Baltimore', '21201', 'Maryland', 'GXu@gmail.com';
EXEC spAddPerson 'Paula', 'Rubio', '1011 Yolanda Circle', 'Berkeley', '94704', 'California', 'PRubio@gmail.com';
EXEC spAddPerson 'Julian', 'Isla', '1011 Yolanda Circle', 'N. Vancouver', 'V7L 4J4', 'British Columbia', 'JIsla@gmail.com';
EXEC spAddPerson 'Jesse', 'Scott', '1013 Holiday Hills Dr.', 'Bremerton', '98312', 'Washington', 'JScott@gmail.com';
EXEC spAddPerson 'Naomi', 'Sanz', '1013 Holiday Hills Dr.', 'Gateshead', 'GA10', 'England', 'NSanz@gmail.com';
EXEC spAddPerson 'Isabella', 'Lee', '1015 Lynwood Drive', 'Metchosin', 'V9', 'British Columbia', 'ILee@gmail.com';
EXEC spAddPerson 'Dawn', 'Yuan', '1019 Carletto Drive', 'Berkeley', '94704', 'California', 'DYuan@gmail.com';
EXEC spAddPerson 'Olivia', 'Blue', '1019 Mt. Davidson Court', 'Burien', '98168', 'Washington', 'OBlue@gmail.com';
EXEC spAddPerson 'Emmanuel', 'Lopez', '1019 Mt. Davidson Court', 'London', 'SW8 4BG', 'England', 'ELopez@gmail.com';
EXEC spAddPerson 'Nathan', 'Yang', '102 Vista Place', 'Santa Monica', '90401', 'California', 'NYang@gmail.com';
EXEC spAddPerson 'Gabrielle', 'Wood', '1020 Book Road', 'Bremerton', '98312', 'Washington', 'GWood@gmail.com';
EXEC spAddPerson 'Katrina', 'Anand', '1020 Carletto Drive', 'Matraville', '2036', 'New South Wales', 'KAnand@gmail.com';
EXEC spAddPerson 'Anthony', 'Jones', '1020 Carletto Drive', 'Santa Cruz', '95062', 'California', 'AJones@gmail.com';
EXEC spAddPerson 'Natalie', 'Reed', '1023 Hawkins Street', 'Lebanon', '97355', 'Oregon', 'NReed@gmail.com';
EXEC spAddPerson 'Dakota', 'Ross', '1024 Walnut Blvd.', 'Colma', '94014', 'California', 'DRoss@gmail.com';
EXEC spAddPerson 'Shawn', 'Goel', '1025 Holly Oak Drive', 'Leeds', 'LE18', 'England', 'SGoel@gmail.com';
EXEC spAddPerson 'Nicole', 'Diaz', '1025 R St.', 'Kirkland', '98033', 'Washington', 'NDiaz@gmail.com';
EXEC spAddPerson 'Wyatt', 'Davis', '1025 Yosemite Dr.', 'Oregon City', '97045', 'Oregon', 'WDavis@gmail.com';
EXEC spAddPerson 'Christy', 'Huang', '1028 Green View Court', 'Chula Vista', '91910', 'California', 'CHuang@gmail.com';
EXEC spAddPerson 'Sydney', 'Evans', '1028 Green View Court', 'Oregon City', '97045', 'Oregon', 'SEvans@gmail.com';
EXEC spAddPerson 'Katherine', 'Baker', '1037 Hayes Court', 'Stoke-on-Trent', 'AS23', 'England', 'KBaker@gmail.com';
EXEC spAddPerson 'Edward', 'Wood', '1039 Adelaide St.', 'West Covina', '91791', 'California', 'EWood@gmail.com';
EXEC spAddPerson 'Johnny', 'Rai', '104 Hilltop Dr.', 'Springwood', '2777', 'New South Wales', 'JRai@gmail.com';
EXEC spAddPerson 'Emily', 'Moore', '104 Kaski Ln.', 'Portland', '97205', 'Oregon', 'EMoore@gmail.com';
EXEC spAddPerson 'Randy', 'Yang', '1040 Greenbush Drive', 'Silverwater', '2264', 'New South Wales', 'RYang@gmail.com';
EXEC spAddPerson 'Roy', 'Ruiz', '1040 Northridge Road', 'London', 'W1X3SE', 'England', 'RRuiz@gmail.com';
EXEC spAddPerson 'Marshall', 'Sun', '1044 San Carlos', 'Cincinnati', '45202', 'Ohio', 'MSun@gmail.com';
EXEC spAddPerson 'Gabriella', 'Perez', '1045 Lolita Drive', 'Torrance', '90505', 'California', 'GPerez@gmail.com';
EXEC spAddPerson 'Erika', 'Gill', '1045 Lolita Drive', 'Townsville', '4810', 'Queensland', 'EGill@gmail.com';
EXEC spAddPerson 'Kathryn', 'Shen', '1047 Las Quebradas Lane', 'North Sydney', '2055', 'New South Wales', 'KShen@gmail.com';
EXEC spAddPerson 'Sharon', 'Yuan', '1048 Burwood Way', 'Hervey Bay', '4655', 'Queensland', 'SYuan@gmail.com';
EXEC spAddPerson 'Victoria', 'Lee', '1048 Las Quebradas Lane', 'Walla Walla', '99362', 'Washington', 'VLee@gmail.com';
EXEC spAddPerson 'Brenda', 'Arun', '1048 Las Quebradas Lane', 'Wollongong', '2500', 'New South Wales', 'BArun@gmail.com';
EXEC spAddPerson 'Alex', 'Scott', '105 Clark Creek Lane', 'Port Macquarie', '2444', 'New South Wales', 'AScott@gmail.com';
EXEC spAddPerson 'Yolanda', 'Luo', '105 Woodruff Ln.', 'Bellingham', '98225', 'Washington', 'YLuo@gmail.com';
EXEC spAddPerson 'Martin', 'Vance', '1050 Creed Ave', 'London', 'W10 6BL', 'England', 'MVance@gmail.com';
EXEC spAddPerson 'Jeremy', 'Roberts', '081, boulevard du Montparnasse', 'Seattle', '98104', 'Washington', 'JRoberts@yahoo.com';
EXEC spAddPerson 'Amanda', 'Ramirez', '1 Smiling Tree Court', 'Los Angeles', '90012', 'California', 'ARamirez@yahoo.com';
EXEC spAddPerson 'Jada', 'Nelson', '100, rue des Rosiers', 'Everett', '98201', 'Washington', 'JNelson@yahoo.com';
EXEC spAddPerson 'Hunter', 'Wright', '1002 N. Spoonwood Court', 'Berkeley', '94704', 'California', 'HWright@yahoo.com';
EXEC spAddPerson 'Sierra', 'Wright', '1005 Fremont Street', 'Colma', '94014', 'California', 'SWright@yahoo.com';
EXEC spAddPerson 'Sarah', 'Simmons', '1005 Valley Oak Plaza', 'Langley', 'V3A 4R2', 'British Columbia', 'SSimmons@yahoo.com';
EXEC spAddPerson 'Mandar', 'Samant', '1005 Valley Oak Plaza', 'London', 'SW6 SBY', 'England', 'MSamant@yahoo.com';
EXEC spAddPerson 'Isaiah', 'Rogers', '1007 Cardinet Dr.', 'El Cajon', '92020', 'California', 'IRogers@yahoo.com';
EXEC spAddPerson 'Ian', 'Foster', '1008 Lydia Lane', 'Burbank', '91502', 'California', 'IFoster@yahoo.com';
EXEC spAddPerson 'Ben', 'Miller', '101 Candy Rd.', 'Redmond', '98052', 'Washington', 'BMiller@yahoo.com';
EXEC spAddPerson 'Sarah', 'Barnes', '1011 Green St.', 'Bellingham', '98225', 'Washington', 'SBarnes@yahoo.com';
EXEC spAddPerson 'Casey', 'Martin', '1013 Buchanan Rd', 'Port Macquarie', '2444', 'New South Wales', 'CMartin@yahoo.com';
EXEC spAddPerson 'Victoria', 'Murphy', '1013 Buchanan Rd', 'Yakima', '98901', 'Washington', 'VMurphy@yahoo.com';
EXEC spAddPerson 'Sydney', 'Rogers', '1016 Park Avenue', 'Burbank', '91502', 'California', 'SRogers@yahoo.com';
EXEC spAddPerson 'Marvin', 'Hernandez', '1019 Book Road', 'Rhodes', '2138', 'New South Wales', 'MHernandez@yahoo.com';
EXEC spAddPerson 'Carlos', 'Carter', '1019 Buchanan Road', 'Woodland Hills', '91364', 'California', 'CCarter@yahoo.com';
EXEC spAddPerson 'Rebekah', 'Garcia', '1019 Candy Rd.', 'Coffs Harbour', '2450', 'New South Wales', 'RGarcia@yahoo.com';
EXEC spAddPerson 'Haley', 'Henderson', '1019 Chance Drive', 'Sedro Woolley', '98284', 'Washington', 'HHenderson@yahoo.com';
EXEC spAddPerson 'Jacob', 'Taylor', '1019 Kenwal Rd.', 'Lake Oswego', '97034', 'Oregon', 'JTaylor@yahoo.com';
EXEC spAddPerson 'Seth', 'Martin', '1019 Pennsylvania Blvd', 'Marysville', '98270', 'Washington', 'SMartin@yahoo.com';
EXEC spAddPerson 'Larry', 'Suarez', '102 Vista Place', 'Milton Keynes', 'MK8 8DF', 'England', 'LSuarez@yahoo.com';
EXEC spAddPerson 'Garrett', 'Vargas', '10203 Acorn Avenue', 'Calgary', 'T2P 2G8', 'Alberta', 'GVargas@yahoo.com';
EXEC spAddPerson 'Abby', 'Martinez', '1023 Hawkins Street', 'Townsville', '4810', 'Queensland', 'AMartinez@yahoo.com';
EXEC spAddPerson 'Justin', 'Thomas', '1023 Riveria Way', 'Burbank', '91502', 'California', 'JThomas@yahoo.com';
EXEC spAddPerson 'Evelyn', 'Martinez', '1023 Riviera Way', 'Oxford', 'OX1', 'England', 'EMartinez@yahoo.com';
EXEC spAddPerson 'Pamela', 'Chapman', '1025 Yosemite Dr.', 'Townsville', '4810', 'Queensland', 'PChapman@yahoo.com';
EXEC spAddPerson 'Kayla', 'Griffin', '1026 Mt. Wilson Pl.', 'Lynnwood', '98036', 'Washington', 'KGriffin@yahoo.com';
EXEC spAddPerson 'Jill', 'Navarro', '1026 Mt. Wilson Pl.', 'South Melbourne', '3205', 'Victoria', 'JNavarro@yahoo.com';
EXEC spAddPerson 'Nathan', 'Walker', '1028 Indigo Ct.', 'Issaquah', '98027', 'Washington', 'NWalker@yahoo.com';
EXEC spAddPerson 'Tabitha', 'Moreno', '1028 Indigo Ct.', 'Warrnambool', '3280', 'Victoria', 'TMoreno@yahoo.com';
EXEC spAddPerson 'Mason', 'Sanchez', '1028 Royal Oak Rd.', 'Burlingame', '94010', 'California', 'MSanchez@yahoo.com';
EXEC spAddPerson 'Natasha', 'Navarro', '1029 Birchwood Dr', 'Burien', '98168', 'Washington', 'NNavarro@yahoo.com';
EXEC spAddPerson 'Kevin', 'Russell', '1029 Birchwood Dr', 'Olympia', '98501', 'Washington', 'KRussell@yahoo.com';
EXEC spAddPerson 'Katelyn', 'Rivera', '1030 Ambush Dr.', 'Bury', 'PE17', 'England', 'KRivera@yahoo.com';
EXEC spAddPerson 'Alfredo', 'Ortega', '1032 Buena Vista', 'North Ryde', '2113', 'New South Wales', 'AOrtega@yahoo.com';
EXEC spAddPerson 'Andrea', 'Campbell', '1032 Coats Road', 'Stoke-on-Trent', 'AS23', 'England', 'ACampbell@yahoo.com';
EXEC spAddPerson 'Jeremy', 'Peterson', '1035 Arguello Blvd.', 'San Diego', '92102', 'California', 'JPeterson@yahoo.com';
EXEC spAddPerson 'Arianna', 'Ramirez', '1036 Mason Dr', 'Port Orchard', '98366', 'Washington', 'ARamirez@yahoo.com';
EXEC spAddPerson 'Mario', 'Sharma', '1039 Adelaide St.', 'Port Macquarie', '2444', 'New South Wales', 'MSharma@yahoo.com';
EXEC spAddPerson 'Adam', 'Collins', '104 Hilltop Dr.', 'Concord', '94519', 'California', 'ACollins@yahoo.com';
EXEC spAddPerson 'Taylor', 'Martin', '1040 Greenbush Drive', 'Newton', 'V2L3W8', 'British Columbia', 'TMartin@yahoo.com';
EXEC spAddPerson 'Gabriel', 'Collins', '1040 Northridge Road', 'Woodland Hills', '91364', 'California', 'GCollins@yahoo.com';
EXEC spAddPerson 'Randall', 'Martin', '1042 Hooftrail Way', 'Newcastle', '2300', 'New South Wales', 'RMartin@yahoo.com';
EXEC spAddPerson 'Samantha', 'Jenkins', '1046 Cloverleaf Circle', 'Shawnee', 'V8Z 4N5', 'British Columbia', 'SJenkins@yahoo.com';
EXEC spAddPerson 'Justin', 'Simmons', '1046 San Carlos Avenue', 'Colma', '94014', 'California', 'JSimmons@yahoo.com';
EXEC spAddPerson 'Ethan', 'Winston', '1047 Las Quebradas Lane', 'Oak Bay', 'V8P', 'British Columbia', 'EWinston@yahoo.com';
EXEC spAddPerson 'Hunter', 'Roberts', '1048 Burwood Way', 'Haney', 'V2W 1W2', 'British Columbia', 'HRoberts@yahoo.com';
EXEC spAddPerson 'Nathaniel', 'Murphy', '105 Woodruff Ln.', 'Oakland', '94611', 'California', 'NMurphy@yahoo.com';
EXEC spAddPerson 'Charles', 'Wilson', '1050 Creed Ave', 'Lebanon', '97355', 'Oregon', 'CWilson@yahoo.com';
EXEC spAddPerson 'Carrie', 'Alvarez', '1050 Greenhills Circle', 'Lane Cove', '1597', 'New South Wales', 'CAlvarez@yahoo.com';
EXEC spAddPerson 'Paige', 'Alexander', '1050 Greenhills Circle', 'Langley', 'V3A 4R2', 'British Columbia', 'PAlexander@yahoo.com';


-- INSERT ALL GIVEN SPONSOR DATA
EXEC spAddSponsor 'VMWare', 'Platinum Sponsor';
EXEC spAddSponsor 'Verizon Digital Media Services', 'Platinum Sponsor';
EXEC spAddSponsor 'Microsoft Corporation (GAP) (GAP Sponsor)', 'Platinum Sponsor';
EXEC spAddSponsor 'Tintri', 'Platinum Sponsor';
EXEC spAddSponsor 'Amazon Web Services, LLC', 'Gold Sponsor';
EXEC spAddSponsor 'Pyramid Analytics (GAP Sponsor)', 'Gold Sponsor';
EXEC spAddSponsor 'Pure Storage', 'Gold Sponsor';
EXEC spAddSponsor 'Profisee', 'Gold Sponsor';
EXEC spAddSponsor 'NetLib Security', 'Silver Sponsor';
EXEC spAddSponsor 'Melissa Data Corp.', 'Silver Sponsor';
EXEC spAddSponsor 'Red Gate Software', 'Silver Sponsor';
EXEC spAddSponsor 'SentryOne', 'Silver Sponsor';
EXEC spAddSponsor 'Hush Hush', 'Bronze Sponsor';
EXEC spAddSponsor 'COZYROC', 'Bronze Sponsor';
EXEC spAddSponsor 'SQLDocKit by Acceleratio Ltd.', 'Bronze Sponsor';
